[project]
name = "scrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "lxml>=6.0.1",
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
]
